home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('story4.urls', namespace='story4')),
    path('story9/', include('story9.urls', namespace='story9')),
    path('books/', include('books.urls', namespace='books')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story1/', include('home.urls', namespace='story1')),
    path('admin/', admin.site.urls),
    
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

# from .views import addActivity
from . import views

app_name = 'story9'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutView, name='logout'),
    path('', views.index, name='index'),
]

story9/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

story9/forms.py
from django import forms
from .models import Profile
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password_first = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_again = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        password_one = self.cleaned_data.get('password_first')
        password_two = self.cleaned_data.get('password_again')
        if password_one != password_two:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email_address)
        if qs.exists():
            raise forms.ValidationError("The email address you've chosen is already registered.")
        return email_address

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from .forms import LoginForm, RegisterForm

User = get_user_model()

# Create your views here.
def index(request):
    context = {
        'title': 'Welcome'
    }
    return render(request, 'story9/index.html', context)

def register(request):
    form = RegisterForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password_first")
        User.objects.create_user(username, email, password)
        return redirect('story9:login')

        
    return render(request, "story9/register.html", context)


def logoutView(request):
    context = {}
    logout(request)
    return render(request, 'story9/logout.html', context)

def loginView(request):
    form = LoginForm(request.POST or None)
    context = {
        'form': form
    }
    
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('story9:index')
        else:
            context["error"]= "Incorrect username or password"
            return render(request, 'story9/login.html', context)

    return render(request, "story9/login.html", context=context)

story9/templates/story9/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Selamat Datang :)</title>
        <link rel="icon" href="{% static 'logo.png' %}" type="image/icon type">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <!-- CSS -->
        <link rel='stylesheet' type='text/css' href="{% static 'story4/style.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Lora:wght@600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </head>

    <body>
        <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-custom fixed-top">
        <a class="navbar-brand" href="{% url 'story4:index' %}"><img src="{% static 'logo.png' %}" style="width:80px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="line"></span>
            <span class="line"></span> 
            <span class="line" style="margin-bottom: 0;"></span>
        </button>
        {% block navbar %}
        {% endblock navbar %}
    </nav>

    {% block main %}
    {% endblock main %}

        <!-- block for js and jquery accordion -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </body>
</html>

story9/templates/story9/index.html
{% extends 'story9/base.html' %} {% load static %} 

{% block navbar %}
<div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'story9:logout' %}">LOGOUT</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'story9:login' %}">LOGIN</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'story9:register' %}">SIGNUP</a>
    </li>
    </ul>
    {% endif %}
</div>
{% endblock navbar %}

{% block main %}
    <div class="container m-5 p-5 text-center">
        {% if user.is_authenticated %}
        <h2 class="text-center">Hello, {{user}}:)</h2>
        <h3>Explore <a style="color: #06647E;" href="{% url 'story4:index'%}">DTYA</a></h3>
        {% else %}
        <h2 class="text-center">Hello!<br>Please Log In or Sign Up to continue :)</h2>
        <div class="text-center">
            <a class="btn btn-warning" href="{% url 'story9:login' %}">Log In</a>
            <a class="btn btn-warning" href="{% url 'story9:register' %}">Sign Up</a>
        </div>
        {% endif %}
    </div>
{% endblock main %}

story9/templates/story9/login.html
{% extends 'story9/base.html' %} {% load static %} 

{% block navbar %}
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story9:register' %}">SIGNUP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story9:index' %}">HOME</a>
        </li>
        </ul>
    </div>
</nav>
{% endblock navbar %}

{% block main %}
<div class="container m-5 p-5 mx-auto">
    <h3>LOG IN</h3>
    <form method="POST">

        {% csrf_token %}
        {{ form.as_p }}
    
        <button type="submit" class="btn btn-warning">Log In</button>
        <a class="btn btn-warning" href="{% url 'story9:index' %}">Cancel</a>
    
    </form>
    <br>
    <h6 class="text-danger">{{ error }}</h6>
    <h6 style="color: #FE7210;">Don't have an account? <a style="color: #06647E;" href="{% url 'story9:register'%}">Sign Up</a></h6 style="color: #FE7210;">
</div>
{% endblock main %}

story9/templates/story9/logout.html
{% extends 'story9/base.html' %} {% load static %} 

{% block navbar %}
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story9:login' %}">LOGIN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'story9:index' %}">HOME</a>
        </li>
        </ul>
    </div>
</nav>
{% endblock navbar %}

{% block main %}
<div class="container m-5 p-5 mx-auto text-center">
    <h2>You've logged out</h2>
    <div class="text-center">
        <a class="btn btn-warning" href="{% url 'story9:login' %}">Log In again</a>
        <a class="btn btn-warning" href="{% url 'story9:index' %}">Home</a>
    </div>
</div>
{% endblock main %}

story9/templates/story9/register.html
{% extends 'story9/base.html' %} {% load static %} 

{% block navbar %}
<div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav ml-auto">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'story9:login' %}">LOGIN</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'story9:index' %}">HOME</a>
    </li>
    </ul>
</div>
</nav>
{% endblock navbar %}

{% block main %}
<div class="container m-5 p-5 mx-auto">
<h3>SIGN UP</h3>
<form method="POST">

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" class="btn btn-warning">Sign Up</button>
    <a class="btn btn-warning" href="{% url 'story9:index' %}">Cancel</a>

</form>
<br>
<p>Already have an account? <a style="color: #06647E;" href="{% url 'story9:login'%}">Log In</a></p>
</div>
{% endblock main %}