home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('story4.urls', namespace='story4')),
    path('story9/', include('story9.urls', namespace='story9')),
    path('books/', include('books.urls', namespace='books')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story1/', include('home.urls', namespace='story1')),
    path('admin/', admin.site.urls),
    
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('choose/<str:id>/', views.pilihjadwal, name='pilihjadwal'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('about/', views.about, name='about'),
    path('skills/', views.skills, name='skills'),
    path('experiences/', views.experiences, name='experiences'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

# from .views import addActivity
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
]

story7/models.py
from django.db import models

# Create your models here.

story7/views.py
from django.shortcuts import render, redirect

# Create your views here.
def index(request):
    return render(request, 'story7/index.html')

story7/templates/story7/dasar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Naifathiya Langitadiva</title>
        <link rel="icon" href="{% static 'logo.png' %}" type="image/icon type">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <!-- CSS -->
        <link rel='stylesheet' type='text/css' href="{% static 'story4/style.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Lora:wght@600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

        {% block meta %} {% endblock meta %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </head>

    <body>
        <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-custom fixed-top">
        <a class="navbar-brand" href="{% url 'story4:index' %}"><img src="{% static 'logo.png' %}" style="width:80px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="line"></span>
            <span class="line"></span> 
            <span class="line" style="margin-bottom: 0;"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:index' %}">STORY 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story4:jadwal' %}">JADWAL</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story6:index' %}">ACTIVITY</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story4:skills' %}">SKILLS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story4:experiences' %}">EXPERIENCES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story4:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story7:index' %}">ME</a>
            </li>
            </ul>
        </div>
    </nav>
        {% block main %} {% endblock main %}

        <!-- block for js and jquery accordion -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </body>
</html>

story7/templates/story7/index.html
{% extends 'story7/dasar.html' %} {% load static %} 

{% block meta %}
<script src="{% static 'jquery-3.5.1.js' %}"></script>
<script src="{% static 'story7.js' %}"></script>
{% endblock meta %}

{% block main %}
<div class="container m-5 p-5 mx-auto">
  <h3 class="text-center">Dtya's Accordion</h3><br>
    <div id="accordion">

      <div id="aktivitas">
          <h3>Aktivitas Saat Ini 
            <span style="float: right;">
              <i class="button-up fas fa-chevron-up"></i>
              <i class="button-down fas fa-chevron-down"></i>
            </span>
          </h3>
          <div>
            <ul>
                <li>Kuliah Online</li>
                <li>Kepanitiaan dan Organisasi</li>
                <li>Menikmati Era NCT2020</li>
            </ul>
          </div>
      </div>

      <div id="organisasi">
          <h3>Pengalaman Organisasi
            <span style="float: right;">
              <i class="button-up fas fa-chevron-up"></i>
              <i class="button-down fas fa-chevron-down"></i>
            </span>
          </h3>
          <div>
              <ul>
                  <li>Sekretaris OSIS SMP Islam Al Azhar 8</li>
                  <li>Wakil Ketua OSIS SMA Islam Al Azhar 4</li>
                  <li>Staf Biro PSDM BEM Fasilkom UI 2020</li>
              </ul>
          </div>
      </div>  

      <div id="kepanitiaan">
          <h3>Pengalaman Kepanitiaan
            <span style="float: right;">
              <i class="button-up fas fa-chevron-up"></i>
              <i class="button-down fas fa-chevron-down"></i>
            </span>
          </h3>
          <div>
              <ul>
                  <li>PJ Lomba Ratoeh Jaroe ALCHEMIST6</li>
                  <li>Bendahara QUATROLYMPIC11</li>
                  <li>Staf Humpub OH Fasilkom 2019</li>
                  <li>Staf Acara Wisgan 2020</li>
                  <li>Staf Seminar COMPFEST12</li>
                </ul>
          </div>
      </div>

      <div id="prestasi">
          <h3>Prestasi
            <span style="float: right;">
              <i class="button-up fas fa-chevron-up"></i>
              <i class="button-down fas fa-chevron-down"></i>
            </span>
          </h3>
          <div>
              <ul>
              <li>Juara Harapan 3 CG Contest BMBC VII</li>
                  <li>Juara Harapan 1 Ratoeh Jaroe Piala Gubernur Aceh 2018</li>
                  <li>Juara 1 Ratoeh Jaroe TOC8</li>
                </ul>
          </div>
      </div>
    </div>
</div>   
 
    {% endblock main %}