home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('story4.urls', namespace='story4')),
    path('story9/', include('story9.urls', namespace='story9')),
    path('books/', include('books.urls', namespace='books')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story1/', include('home.urls', namespace='story1')),
    path('admin/', admin.site.urls),
    
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

# from .views import addActivity
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/',views.addActivity,name='addActivity'),
    path('list/', views.listActivity, name='listActivity'),
    path('register/<int:task_id>/', views.register, name='register'),
    path('delete/<int:delete_id>/', views.delete, name='delete'),
]

story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    nama_kegiatan = models.CharField(max_length=100)
    deskripsi = models.CharField(max_length=1000)

    def __str__(self):
        return self.nama_kegiatan

class Person(models.Model):
    nama = models.CharField(max_length=64)
    kegiatan = models.ForeignKey(
        Activity,
        on_delete=models.CASCADE, 
        null=True, 
        blank=True)

    def __str__(self):
        return self.nama

story6/forms.py
from django import forms
# from .models import Activity, Person

# class ActivityForm(forms.ModelForm):
#     class Meta:
#         model = Activity
#         fields = [
#             'nama_kegiatan',
#             'deskripsi'
#         ]

# class PersonForm(forms.ModelForm):
#     kegiatan = forms.
#     class Meta:
#         model = Person
#         fields = [
#             'nama'
#         ]

class ActivityForm(forms.Form):
    nama_kegiatan = forms.CharField(
        label="Nama kegiatan",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-60',
            }
        )
    )

    deskripsi = forms.CharField(
        label="Deskripsi",
        max_length=1000,
        widget=forms.Textarea(
            
        )
    )


class PersonForm(forms.Form):
    nama = forms.CharField(
        label="Nama",
        max_length=64,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

story6/views.py
from django.shortcuts import render, redirect
from .models import Activity, Person
from .forms import ActivityForm, PersonForm
from datetime import datetime

# Create your views here.
def index(request):
    return render(request, 'story6/index.html')

def addActivity(request):
    activity_form = ActivityForm()
    if request.method == "POST":
        activity_form_input = ActivityForm(request.POST)
        if activity_form_input.is_valid():
            data = activity_form_input.cleaned_data
            activity_input = Activity()
            activity_input.nama_kegiatan = data['nama_kegiatan']
            activity_input.deskripsi = data['deskripsi']
            activity_input.save()
            return redirect('story6:index')
        else:
            return render(request, 'story6/addactivity.html', {'form': activity_form, 'status': 'failed'})
    context = {
        'form': activity_form
    }
    return render(request, 'story6/addactivity.html', context)


def listActivity(request):
    activities = Activity.objects.all()
    persons = Person.objects.all()
    context = {
        'activities' : activities,
        'persons' : persons
    }
    return render(request, 'story6/listActivity.html', context)


def delete(request, delete_id):
    activity = Activity.objects.all()
    person = Person.objects.all()
    print(delete_id)
    person_to_delete = Person.objects.get(id=delete_id)
    person_to_delete.delete()
    
    return redirect('story6:listActivity')


def register(request, task_id):
    form_person = PersonForm()

    if request.method == "POST":
        form_person_input = PersonForm(request.POST)
        if form_person_input.is_valid():
            data = form_person_input.cleaned_data
            newPerson = Person()
            newPerson.nama = data['nama']
            newPerson.kegiatan = Activity.objects.get(id=task_id)
            newPerson.save()
            return redirect('story6:listActivity')
        else:
            return render(request, 'story6/register.html', {'form': form_person, 'status': 'failed'})
    else:
        return render(request, 'story6/register.html', {'form': form_person})

story6/templates/story6/addactivity.html
{% extends 'story4/base.html' %} {% load static %} 

{% block main %}
    <div class="container m-5 p-5 mx-auto">
    <h2>Add Activity</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br>
        <button class="btn btn-warning" type="Submit">Submit</button>
        <a class="btn btn-warning" href="{% url 'story6:listActivity' %}">Cancel</a>
    </form>
    </div>
{% endblock main %}

story6/templates/story6/index.html
{% extends 'story4/base.html' %} {% load static %} 

{% block main %}
    <div class="container m-5 p-5">

    <br><br><br><br><br><br><br>
    <div class="flex flex-col h-90 w-75">
        <h2>What kind of activity you want to do?<br>Let's join the fun together!</h2>
        <a href="{% url 'story6:addActivity'%}" class="btn btn-warning text-sm-center ">Add Activity</a>
    
        <a href="{% url 'story6:listActivity'%}" class="btn btn-warning text-sm-center">List Activity</a>
                
    </div>



    </div>
{% endblock main %}

story6/templates/story6/listActivity.html
{% extends 'story4/base.html' %} {% load static %} 

{% block main %}
    <div class="container m-5 p-5">
        <h2>List Activity</h2>
        <div class="row w-100 justify-content-center">
            {% for activity in activities %}
            <div class="col-4 m-4 p-4 rounded border">
                <ul class="list-group">
                    <li class="list-group-item list-group-item-secondary"> <b> {{ activity.nama_kegiatan }} </b> </li>
    
                    {% for person in persons %}
                    {% if person.kegiatan == activity %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between">
                            {{ person.nama }}

                                <a class="btn btn-danger" href="{% url 'story6:delete' delete_id=person.pk %}">Delete</a>
    
                        </div>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
    
                <div>
                    <br>
                    <a href="{%url 'story6:register' task_id=activity.pk%}" class="btn btn-warning">Register Yourself!</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="text-sm-center">
            <a href="{% url 'story6:addActivity'%}" class="btn btn-warning text-sm-center ">Add Activity</a>
        </div>

    </div>
    <br><br><br><br><br><br><br>
{% endblock main %}

story6/templates/story6/register.html
{% extends 'story4/base.html' %} {% load static %} 

{% block main %}
    <div class="container m-5 p-5 mx-auto">
    <h2>Register</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br>
        <button class="btn btn-warning" type="Submit">Submit</button>
        <a class="btn btn-warning" href="{% url 'story6:listActivity' %}">Cancel</a>
    </form>
    </div>
{% endblock main %}