home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('story4.urls', namespace='story4')),
    path('story9/', include('story9.urls', namespace='story9')),
    path('books/', include('books.urls', namespace='books')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story1/', include('home.urls', namespace='story1')),
    path('admin/', admin.site.urls),
    
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('choose/<str:id>/', views.pilihjadwal, name='pilihjadwal'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('about/', views.about, name='about'),
    path('skills/', views.skills, name='skills'),
    path('experiences/', views.experiences, name='experiences'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
]

story4/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Matkul(models.Model):
    nama_matkul = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    jumlah_sks = models.IntegerField(validators=[MinValueValidator(1),
                                       MaxValueValidator(6)])
    deskripsi = models.TextField(blank=False, null=True)
    term = models.CharField(max_length=30)
    ruang_kelas = models.CharField(max_length=6)

    def __str__(self):
        return "{}.{}".format(self.id,self.nama_matkul)

story4/forms.py
from django import forms
from .models import Matkul

class Input_Form(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = ['nama_matkul',
            'dosen',
            'jumlah_sks',
            'deskripsi',
            'term',
            'ruang_kelas'
        ]

story4/views.py
from django.shortcuts import render, redirect
from .forms import Input_Form
from .models import Matkul


# Create your views here.
def index(request):
    return render(request, 'story4/index.html')

def about(request):
    return render(request, 'story4/about.html')

def skills(request):
    return render(request, 'story4/skills.html')

def experiences(request):
    return render(request, 'story4/experiences.html')

def jadwal(request):
    posts = Matkul.objects.all()

    context = {
        'posts' : posts
    }

    return render(request, 'story4/jadwal.html', context)

def pilihjadwal(request,id):
    matkul = Matkul.objects.get(id=id)

    context = {
        'matkul' : matkul
    }

    return render(request, 'story4/pilihjadwal.html', context)

def create(request):
    form = Input_Form(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()

            return redirect('story4:jadwal')

    context = {
        'form': form
    }
    return render(request, 'story4/create.html', context)

def delete(request, id):
    matkul = Matkul.objects.get(id=id)
    matkul.delete()
    return redirect('story4:jadwal')

story4/templates/story4/about.html
{% extends 'story4/base.html' %} {% load static %} {% block main %}
<img class="img-responsive" src="{% static 'me.jpg' %}" alt="Chania" width="100%" height="auto"> 
<br><br><br>
<div class="container">   
    <div class="row">
        <div class="col-sm-6 text-right">
            <h2>About Me</h2>
        </div>
        <div class="col-sm-6">
            <h3>Naifathiya Langitadiva</h3>
            <p>Undergraduate Information System at University of Indonesia<br><br>
                I am a person who is positive about every aspect of life. I also have my own principle to live my life that I won't go full throttle. 
                Instead, I will walk slowly enjoying every step of the journey. At my own pace, following my own rythms.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 text-right">
            <h2>Contact</h2>
        </div>
        <div class="col-sm-6" style="color: #FE7210;">
            <p><i class="fa fa-envelope"></i>&nbsp;&nbsp; naifathiyald@gmail.com
            <br><i class="fa fa-envelope"></i>&nbsp;&nbsp; naifathiya.langitadiva@ui.ac.id</p>
        </div>
    </div>   
</div> 
{% endblock main %}

story4/templates/story4/base.html
{% load static %}
<html>
<head>
    <title>Naifathiya Langitadiva</title>
    <link rel="icon" href="{% static 'logo.png' %}" type="image/icon type">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- CSS -->
    <link rel='stylesheet' type='text/css' href="{% static 'story4/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-custom fixed-top">
        <a class="navbar-brand" href="{% url 'story4:index' %}"><img src="{% static 'logo.png' %}" style="width:80px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="line"></span>
            <span class="line"></span> 
            <span class="line" style="margin-bottom: 0;"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:index' %}">STORY 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story4:jadwal' %}">JADWAL</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story6:index' %}">ACTIVITY</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story4:skills' %}">SKILLS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story4:experiences' %}">EXPERIENCES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story4:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story7:index' %}">ME</a>
            </li>
            </ul>
        </div>
    </nav>
    
    <!-- Body -->
    {% block main %} {% endblock main %}

    <!-- Footer -->
    <div class="d-flex justify-content-between mb-3 mt-5">
        <div class="p-2"></div>
        <div class="copyright p-2 text-center">© 2020 Naifathiya Langitadiva. All Rights Reserved.</div>
        <div class="p-2">
            <div class="media">
                <ul class="list-unstyled float-left">
                    <li><a href="https://www.instagram.com/dtya__/"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="https://www.linkedin.com/in/naifathiya-langitadiva-54454b179"><i class="fab fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </div> 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story4/templates/story4/create.html
{% extends 'story4/base.html' %} {% load static %} 

{% block main %}
    <div class="container m-5 p-5 mx-auto">
    <h2>Daftar Mata Kuliah</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br>
        <button class="btn btn-warning" type="Submit">Submit</button>
        <a class="btn btn-warning" href="{% url 'story4:jadwal' %}">Cancel</a>
    </form>
    </div>
{% endblock main %}

story4/templates/story4/experiences.html
{% extends 'story4/base.html' %} {% load static %} {% block main %}
<div class="row">
    <div class="col-md-6 p-5">
        <br><br>
        <h2>Education<br>Background</h2>
        <p>SD Islam Al Azhar 9<br>2007 - 2013</p>
        <p>SMP Islam Al Azhar 8<br>2013 - 2016</p>
        <p>SMA Islam Al Azhar 4<br>2016 - 2019</p>
        <p>Universitas Indonesia<br>2019 - 2023</p> 
    </div>
    <div class="col-md-6 p-5" style="background-color: #0D9CA4;"> 
        <br><br>
        <h2 style="color: #FBEEDD;">Comittee<br>Experiences</h2>
        <div class="img__wrap">
            <img class="img__img" src="{% static 'psdm.jpg' %}" />
            <p class="img__description">Staff PSDM<br>BEM Fasilkom UI 2020</p>
        </div>
        <div class="img__wrap">
            <img class="img__img" src="{% static 'wisgan.jpg' %}" />
            <p class="img__description">Staff Acara<br>Wisuda Ganjil Fasilkom 2020</p>
        </div>
        <div class="img__wrap">
            <img class="img__img" src="{% static 'oh.jpg' %}" />
            <p class="img__description">Staff Humas & Publikasi<br>Open House Fasilkom 2019</p>
        </div>
        <div class="img__wrap">
            <img class="img__img" src="{% static 'osis.jpg' %}" />
            <p class="img__description">Wakil Ketua OSIS<br>SMA Islam Al Azhar 4 2017/2018</p>
        </div>
    </div>
</div>
{% endblock main %}

story4/templates/story4/index.html
{% extends 'story4/base.html' %} {% load static %} {% block main %}
<div class="container m-5 p-5 mx-auto">
    <br><br><br><br><br><br><br>
    <h1>Hi,<br>My name is Dtya :)</br></h1>
    <h4>Scroll down to know more!</h4>
</div>

<!-- Hover image -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="cont">
                <img src="{% static 'abt.jpg' %}" class="image">
                <div class="overlay">
                  <div class="text"><a class="nav-link2" href="{% url 'story4:about' %}">About Me</a></div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="cont">
                <img src="{% static 'ski.jpg' %}" class="image">
                <div class="overlay">
                  <div class="text"><a class="nav-link2" href="{% url 'story4:skills' %}">Skills & Interests</a></div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="cont">
                <img src="{% static 'exp.JPG' %}" class="image">
                <div class="overlay">
                  <div class="text"><a class="nav-link2" href="{% url 'story4:experiences' %}">Experiences</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

story4/templates/story4/jadwal.html
{% extends 'story4/base.html' %} {% load static %} 

{% block main %}
    <div class="container m-5 p-5">
    <h2>Jadwal Kuliah</h2>

        <table class="table">
            <thead>
              <tr class="bg-info">
                <th scope="col">No</th>
                <th scope="col">Mata Kuliah</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                  <tr>
                    <th class="align-middle" scope="row">{{ forloop.counter }}</th>
                    <td class="align-middle"><a class="text-dark" href="{% url 'story4:pilihjadwal' post.id %}">{{ post.nama_matkul }}</a></td>
                    <td class="align-middle text-center"><a class="btn btn-danger" href="{% url 'story4:delete' post.id %}">Delete</a></td>
                  </tr>
                {% endfor %}
            </tbody>
          </table>
          <a class="btn btn-warning" href="{% url 'story4:create' %}">Add Matkul</a>
    </div>
{% endblock main %}

story4/templates/story4/pilihjadwal.html
{% extends 'story4/base.html' %} {% load static %} 

{% block main %}
    <div class="container m-5 p-5">
    <h2>{{ matkul.nama_matkul }}</h2>
        <table class="table text-center">
            <thead>
              <tr class="bg-info">
                <th class="align-middle" scope="col">Dosen</th>
                <th class="align-middle" scope="col">Jumlah SKS</th>
                <th class="align-middle" scope="col">Deskripsi</th>
                <th class="align-middle" scope="col">Term</th>
                <th class="align-middle" scope="col">Ruang Kelas</th>
              </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="align-middle">{{ matkul.dosen }}</td>
                    <td class="align-middle">{{ matkul.jumlah_sks }}</td>
                    <td class="align-middle">{{ matkul.deskripsi }}</td>
                    <td class="align-middle">{{ matkul.term }}</td>
                    <td class="align-middle">{{ matkul.ruang_kelas }}</td>
                </tr>
            </tbody>
          </table>
          <a class="btn btn-warning" href="{% url 'story4:jadwal' %}">Back to Jadwal</a>
    </div>
{% endblock main %}

story4/templates/story4/skills.html
{% extends 'story4/base.html' %} {% load static %} {% block main %}
<div class="container m-5 p-5">
    <h2 class="text-right">Skills</h2>
    <p>Organizational Skills</p>
    <div class="progress">
      <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:80%;"></div>
    </div>

    <p>Communication</p>
    <div class="progress">
      <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:77%"></div>
    </div>

    <p>English</p>
    <div class="progress">
      <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%"></div>
    </div>

    <p>Basic Programming</p>
    <div class="progress">
      <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%"></div>
    </div>

    <br><br><br>
    <h2 style="color: #0D9CA4">Interests</h2>
    <br>
    <div class="row justify-content-center">
        <div class="col-sm-4 text-center">
            <img src="{% static 'translating.png' %}" alt="Language" style="width:50%">
            <br><p>Languages</p>
        </div>
        <div class="col-sm-4 text-center">
            <img src="{% static 'musical-notes.png' %}" alt="Music & Drama" style="width:50%">
            <br><p>K-Music & Drama</p>
        </div>
        <div class="col-sm-4 text-center">
            <img src="{% static 'world.png' %}" alt="Travel" style="width:50%">
            <br><p>Travel</p>
        </div>
    </div>
</div>
<br><br><br>
{% endblock main %}